permissions:
  contents: write

on:
  release:
    types: [created]

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set env
      id: set_env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

    - name: Install prerequisites
      run: sudo apt-get update && sudo apt-get install -y libc6-dev libgl1-mesa-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev libasound2-dev pkg-config

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.2'

    - name: Build
      run: go build -o apples-and-pears_linux_amd64

    - name: Upload binaries to release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "apples-and-pears_linux_amd64"
        body: "Please enjoy new release"
        allowUpdates: true